openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:9000
    description: locally hosted server for local development purposes
paths:
  /test:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "test"
      responses:
        '200':
          description: OK
  /addemployee:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "addemployeeGet"
      responses:
        '200':
          description: OK
  /addemployees:
    post:
      description: "Upload of employee data"
      operationId: "addemployeesPost"
      parameters:
        - in: query
          name: employeeEndsBefore
          schema:
            type: string
          required: false
          description: If the employee end date is before this date then the employee is not loaded.
      requestBody: 
        description: The content to be upload should be JSON format as per the given schema, either directly in post of via a file.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                # 'file' will be the field name in this multipart request
                file:
                  type: string
                  format: base64
      responses:
        '202':
          description: Request to upload file has been succesfully.   Response contains operational url to poll for upload status.
        "400":
          description: "Invalid status value"
  /employee-count-by-department-code:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "employee-count-by-department-code"
      parameters:
        - in: query
          name: departmentCode
          schema:
            type: string
          required: true
          description: String deparment-code (e.g., AABB).  Department codes are strings encoding a hierarchy where the prefix is higher up the hierarchy (e.g., A->AA->AAA->AAAA)
        - in: query
          name: asOf
          schema:
            type: string
          required: true
          description: The date on which to count employees in the organization
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employee"
        '500':
          description: Internal error, most likely caused by a failure to connect to storage.
        '400':
          description: Poorly formed request, most commonly related to the query parameters.
  /employee-department-history:
    get:
      description: get the history of which department an employee has gone through.
      operationId: "employeeDepartmentHistory"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employeeDepartmentEpocs"
  /employee-role-history:
    get:
      description: get the history of which role an employee has gone through.
      operationId: "employeeRoleHistory"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employeeRoleEpocs"
  /department-history:
    get:
      description: get the history evolution of a department showing change is size over time and movement of people in and out
      operationId: "departmentHistory"
      parameters:
        - in: query
          name: departmentCode
          schema:
            type: string
          required: true
          description: String deparment-code (e.g., AABB).  Department codes are strings encoding a hierarchy where the prefix is higher up the hierarchy (e.g., A->AA->AAA->AAAA)
        - in: query
          name: startDate
          schema:
            type: string
          required: true
          description: The starting point for the history
        - in: query
          name: endDate
          schema:
            type: string
          required: false
          description: The ending point for the history, if not provided it is assume to be the date of the call ("today")
        - in: query
          name: dateStep
          schema:
            $ref: "#/components/schemas/dateStep"
          required: false
          description: this is the date granularity step between sample points of the history
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/departmentHistory"
  /department-codes:
    get:
      description: get a list of department codes as of a given date
      operationId: "department-codes"
      parameters:
        - in: query
          name: asOf
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/sparql-results+xml:
              schema:
                type: string
            application/sparql-results+json:
              schema:
                type: string
            application/x-binary-rdf-results-table:
              schema:
                type: string
  /upload:
    post:
      description: upload a binary file
      operationId: "upload"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                # 'file' will be the field name in this multipart request
                file:
                  type: string
                  format: base64
      responses:
        '202':
          description: Request to upload file has been succesfully.   Response contains operational url to poll for upload status.

  /operations/load/{requestid}:
    get:
      description: Pollable end-point to check the status of the load
      operationId: "operationsLoadingStatus"
      parameters:
        - in: path
          name: requestid
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/addEmployeeLoadStatus"

components:
  schemas:
    employee:
      type: object
      properties:
        employee_id:
          type: string
        system_id:
          type: string
        firstName:
          type: string
        secondName:
          type: string
        jobTitle:
          type: string
        department:
          type: string
        departmentStartDate:
          type: string
          example: "2019-05-17"
        departmentEndDate:
          type: string
          example: "2019-05-17"
        employmentStartDate:
          type: string
          example: "2019-05-17"
        employementEndDate:
          type: string
          example: "2019-05-17"

    employees:
      type: array
      items:
        $ref: "#/components/schemas/employee"

    employeeDepartmentEpoc:
      type: object
      properties:
        employeeId:
          type: string
        department:
          type: string
          example: "ABCD1"
        startdate:
          type: string
          example: "2019-05-17"
        enddate:
          type: string
          example: "2019-05-17"

    employeeDepartmentEpocs:
      type: object
      properties:
        employeeId:
          type: string
        epoc:
          type: array
          items:
            $ref: "#/components/schemas/employeeDepartmentEpoc"

    employeesDepartmentEpocs:
      type: array
      items:
        $ref: "#/components/schemas/employeeDepartmentEpocs"
    
    employeeRoleEpoc:
      type: object
      properties:
        role:
          type: string
          example: "Vice President"
        startdate:
          type: string
          example: "2019-05-17"
        enddate:
          type: string
          example: "2019-05-17"

    employeeRoleEpocs:
      type: array
      items:
        $ref: "#/components/schemas/employeeRoleEpoc"

    dateStep:
      type: string
      enum:
            - day
            - week
            - month
            - year

    departmentHistory:
      type: object
      properties:
        startDate:
          type: string
          example: "2019-05-17"
        endDate:
          type: string
          example: "2019-05-17"
        dateStep:
          $ref: "#/components/schemas/dateStep"
        history:
          type: array
          items:
            $ref: "#/components/schemas/historicPoint"

    historicPoint:
      type: object
      properties:
        department:
          type: string
          example: "ABCD1"
        date:
          type: string
          example: "2019-05-17"
        size:
          type: integer
          example: 23
        joiners:
          type: array
          items:
            $ref: "#/components/schemas/employee"
        leavers:
          type: array
          items:
            $ref: "#/components/schemas/employee"
        members:
          type: array
          items:
            $ref: "#/components/schemas/employee"

    addEmployeeLoadStatus:
      type: object
      properties:
        resourceLocation:
          type: string
        requestId:
          type: string
        createdDateTime:
          type: string
        completedDateTime:
          type: string
        entriesProgressed:
          type: integer
        status:
          type: string
          enum: [processing, complete, error]
        error:
          type: string