# This query returns all members of an organization who were members
# of the organization at a given time. The time is specified by the
# date1 variable. The query returns the member and the time interval
prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?member ?date1 ?date2 WHERE {
    ?pid rdf:type foaf:Person.
    ?member org:organization ?org.
    ?member org:member ?pid.
    ?member org:memberDuring ?interval.
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
  	?start time:inXSDDateTime ?date1.
  	?end time:inXSDDateTime ?date2
  	filter(?date1 <= "2009-11-02T09:00:00Z"^^xsd:dateTime).
}


# This query returns all members of an organization with a given 
# corporate title
prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?member ?date1 ?date2 WHERE {
    ?pid rdf:type foaf:Person.
    ?member org:role ?role.
    ?member org:member ?pid.
    ?member org:memberDuring ?interval.
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
  	?start time:inXSDDateTime ?date1.
  	?end time:inXSDDateTime ?date2.
    filter(?date1 <= "2022-12-17T08:00:00Z"^^xsd:dateTime).
    filter(?date2 >= "2022-12-17T08:00:00Z"^^xsd:dateTime).
}

# query to counter the number of people in an organization at a given time
prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (count(?member) as ?count) WHERE {
    ?member org:organization ?org.
    ?member org:memberDuring ?interval.
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
  	?start time:inXSDDateTime ?date1.
  	?end time:inXSDDateTime ?date2.
  	filter(?date1 <= "2012-12-17T08:00:00Z").
    filter(?date2 >= "2012-12-17T08:00:00Z").
}

# count the number of people in a specific organization at a given time
prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?member ?parentorg ?org WHERE {
  	?parentorg org:name "AB".                   #find parent organization with given name for which you want to count employees
    ?member org:organization ?org.              # find all members of the organization
  	?org org:subOrganizationOf* ?parentorg.     # where the organization is a suborganization of the parent organization
    ?member org:memberDuring ?interval.         # determine when the member was a member of the organization
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
  	?start time:inXSDDateTime ?date1.
  	?end time:inXSDDateTime ?date2.
  	filter(?date1 <= "2012-12-17T08:00:00Z").   # check that the time the person was a member satisfies the time criteria
    filter(?date2 >= "2012-12-17T08:00:00Z").
}


# list of departments in an organization
prefix org: <http://www.w3.org/ns/org#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?org where {
  ?org rdf:type org:FormalOrganization.
  filter not exists {
    ?org org:subOrganizationOf{2,} ?parentorg
  }
}

# count the number of people in a specific organization at a given time
prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?org where {
  	?org rdf:type org:FormalOrganization.
    ?member org:organization ?org.              # find all members of the organization
    ?member org:memberDuring ?interval.         # determine when the member was a member of the organization
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
  	?start time:inXSDDateTime ?date1.
  	?end time:inXSDDateTime ?date2.
  	filter(?date1 <= "2012-12-17T08:00:00Z").   # check that the time the person was a member satisfies the time criteria
    filter(?date2 >= "2012-12-17T08:00:00Z").
}

# find an employees organizations with start and end departments
prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?member ?org ?minStart ?maxEnd
where {
    ?member org:organization ?org.              # find all members of the organization
    {
      optional {
        select ?org (min(?date1) as ?minStart) (max(?date2) as ?maxEnd)
        where {
              ?member org:memberDuring ?interval.			# determine when the member was a member of the organization
              ?interval time:hasBeginning ?start.
              ?interval time:hasEnd ?end.
              ?start time:inXSDDateTime ?date1.
              ?end time:inXSDDateTime ?date2.
        }
        group by ?org ?minStart ?maxEnd
      }
      
    }
}

prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?person ?org ?minStart ?maxEnd
where {
    ?person pid:pid "e10".
    ?org org:member ?person.
    ?member org:organization ?org.              # find all members of the organization
    {
      optional {
        select ?org (min(?date1) as ?minStart) (max(?date2) as ?maxEnd)
        where {
              ?member org:memberDuring ?interval.			# determine when the member was a member of the organization
              ?interval time:hasBeginning ?start.
              ?interval time:hasEnd ?end.
              ?start time:inXSDDateTime ?date1.
              ?end time:inXSDDateTime ?date2.
        }
        group by ?member ?org ?minStart ?maxEnd
      }
    }
}

prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?person ?org ?date1 ?date2
where {
    ?person pid:pid "e10".
    ?org org:member ?person.
    ?member org:organization ?org.              # find all members of the organization
    ?member org:memberDuring ?interval.			# determine when the member was a member of the organization
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
    ?start time:inXSDDateTime ?date1.
    ?end time:inXSDDateTime ?date2.
}

prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

select ?member ?org ?date1 ?date2
where {
    ?member org:organization ?org.              # find all members of the organization
    ?member org:memberDuring ?interval.			# determine when the member was a member of the organization
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
    ?start time:inXSDDateTime ?date1.
    ?end time:inXSDDateTime ?date2.
}
order by DESC(?member) DESC(?date1)

prefix : <http://example.org/id#>
prefix csorg: <http://example.org/org#>
prefix foaf: <http://xmlns.com/foaf/0.1#>
prefix org: <http://www.w3.org/ns/org#>
prefix time: <http://www.w3.org/2006/time#>
prefix pid: <http://example.org/pid#>
prefix interval: <http://example.org/interval#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?member ?org ?date1 ?date2
where {
    ?member org:organization ?org.              # find all members of the organization
    ?member org:memberDuring ?interval.			# determine when the member was a member of the organization
    ?interval time:hasBeginning ?start.
    ?interval time:hasEnd ?end.
    ?start time:inXSDDateTime ?date1.
    ?end time:inXSDDateTime ?date2.
}
group by ?member ?org ?date1 ?date2
