openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:9000
    description: locally hosted server for local development purposes
paths:
  /test:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "test"
      responses:
        '200':
          description: OK
  /addemployee:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "addemployeeGet"
      responses:
        '200':
          description: OK
    post:
      description: "Simple test end-point returning a Hello World!"
      operationId: "addemployeePost"
      requestBody: 
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/employees"
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid status value"
  /employee-count-by-department-code:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "employee-count-by-department-code"
      parameters:
        - in: query
          name: department-code
          schema:
            type: string
          required: true
          description: String deparment-code (e.g., AABB).  Department codes are strings encoding a hierarchy where the prefix is higher up the hierarchy (e.g., A->AA->AAA->AAAA)
        - in: query
          name: as-of
          schema:
            type: string
          required: true
          description: The date on which to count employees in the organization
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employee"


components:
  schemas:
    employee:
      type: object
      properties:
        employee_id:
          type: string
        system_id:
          type: string
        firstName:
          type: string
        secondName:
          type: string
        jobTitle:
          type: string
        department:
          type: string
        departmentStartDate:
          type: string
          format: date
        departmentEndDate:
          type: string
          format: date
        employmentStartDate:
          type: string
          format: date
        employementEndDate:
          type: string
          format: date

    employees:
      type: array
      items:
        $ref: "#/components/schemas/employee"