openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:9000
    description: locally hosted server for local development purposes
paths:
  /test:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "test"
      responses:
        '200':
          description: OK
  /addemployee:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "addemployee"
      responses:
        '200':
          description: OK
    post:
      description: "Simple test end-point returning a Hello World!"
      operationId: "addemployee"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/employee-data"
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid status value"



components:
  schemas:
    employee-data:
      type: object
      properties:
        context:
          type: string