openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:9000
    description: locally hosted server for local development purposes
paths:
  /test:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "test"
      responses:
        '200':
          description: OK
  /addemployee:
    get:
      description: "Simple test end-point returning a Hello World!"
      operationId: "addemployee"
      responses:
        '200':
          description: OK
